### ISSUE TITLE
fail upgrade to storj-framer on Ubunto 16.04

### ISSUE THREAD

**Issue by maroshi** [zannen/docker-storj-farmer#1]
Wanted to upgrade driveshare-farmer to storj-farmer
Uninstalled datashare-farmer successfuly
$sudo apt-get purge datashare
Downloaded the package and installing it failed.
Here is a copy/paste from the install attempt:
**----------------------------------------------------------**
$ sudo apt-get install ./storj-farmer-gui_0.7.2.amd64.deb
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Note, selecting 'storj-farmer-gui' instead of './storj-farmer-gui_0.7.2.amd64.deb'
The following packages were automatically installed and are no longer required:
  libexpat1-dev libpython-all-dev libpython-dev libpython2.7-dev python-all python-all-dev python-dev python-pip
  python-pip-whl python-pkg-resources python-setuptools python-wheel python2.7-dev
Use 'sudo apt autoremove' to remove them.
The following NEW packages will be installed:
  storj-farmer-gui
0 upgraded, 1 newly installed, 0 to remove and 6 not upgraded.
Need to get 0 B/36.6 MB of archives.
After this operation, 168 MB of additional disk space will be used.
Get:1 /home/dudi/Downloads/storj-farmer-gui_0.7.2.amd64.deb storj-farmer-gui amd64 0.7.2 [36.6 MB]
Selecting previously unselected package storj-farmer-gui.
(Reading database ... 191634 files and directories currently installed.)
Preparing to unpack .../storj-farmer-gui_0.7.2.amd64.deb ...
Unpacking storj-farmer-gui (0.7.2) ...
Processing triggers for gnome-menus (3.13.3-6ubuntu3) ...
Processing triggers for desktop-file-utils (0.22-1ubuntu5) ...
Processing triggers for bamfdaemon (0.5.3~bzr0+16.04.20160415-0ubuntu1) ...
Rebuilding /usr/share/applications/bamf-2.index...
Processing triggers for mime-support (3.59ubuntu1) ...
Setting up storj-farmer-gui (0.7.2) ...
ln: failed to create symbolic link '/usr/local/bin/driveshare': File exists
dpkg: error processing package storj-farmer-gui (--configure):
 subprocess installed post-installation script returned error exit status 1
Errors were encountered while processing:
 storj-farmer-gui
E: Sub-process /usr/bin/dpkg returned an error code (1)
**----------------------------------------------------------**
Removed /usr/local/bin/driveshare and retried.
Success.
I believe this will be issued with other platforms as well.

**Comment by zannen** [comment]
I don't think this is the right place for your issue. Try the [storj farmer-gui issue list](https://github.com/Storj/farmer-gui/issues/).
